version: '3.8'

services:
  app:
    platform: linux/amd64
    container_name: survey-application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/survey
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    platform: linux/amd64
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: survey
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db-data:
